import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  errorPill: {
    backgroundColor: '#fee2e2',
    color: '#b91c1c',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '85%',
    minHeight: '70%',
  },
  header: { flexDirection: 'row', marginBottom: 20 },
  title: { fontSize: 20, fontWeight: '700' },
  detail: { color: '#555', fontSize: 14, marginTop: 6 },
  logo: { width: 90, height: 90, borderRadius: 10 },
  section: { fontSize: 18, fontWeight: 'bold', marginBottom: 10 },

  slotCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 14,
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },

  calHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  calHeaderTitle: { fontSize: 14, fontWeight: '700', color: '#111827' },
  navArrow: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2563EB',
    paddingHorizontal: 8,
  },

  weekRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  weekLabel: { flex: 1, textAlign: 'center', fontSize: 13, fontWeight: '600' },
  gridRow: { flexDirection: 'row', alignItems: 'center' },
  dayCellPad: { width: '14.2857%', aspectRatio: 1 },
  dayCell: {
    width: '14.2857%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 6,
  },
  dayCellActive: { backgroundColor: '#2563EB', borderColor: '#2563EB' },
  dayText: { fontSize: 16, fontWeight: '600', color: '#000' },
  dayTextActive: { color: '#fff' },
  slotRow: { paddingVertical: 6 },
  slotChip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#fff',
  },
  slotChipActive: { backgroundColor: '#dbeafe', borderColor: '#2563EB' },
  slotChipText: { color: '#000', fontWeight: '600' },
  slotChipTextActive: { color: '#000', fontWeight: '700' },
  summaryCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 14,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 13,
    color: '#475569',
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0F172A',
    flexShrink: 1,
    textAlign: 'right',
    marginLeft: 12,
  },
  searchWrapper: {
    position: 'absolute',
    top: 46,
    left: 60,
    right: 16,
    zIndex: 20,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'right',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#000',
  },
  searchClear: {
    padding: 6,
  },
  searchSuggestions: {
    marginTop: 6,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    maxHeight: 220,
    overflow: 'hidden',
  },
  suggestionItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  suggestionTitle: {
    fontWeight: '600',
    color: '#0F172A',
  },
  suggestionSubtitle: {
    fontSize: 12,
    color: '#475569',
    marginTop: 2,
  },
  searchEmpty: {
    padding: 12,
    color: '#94A3B8',
  },
  bookBtn: {
    backgroundColor: '#007AFF',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 20,
  },
  bookText: { color: 'white', fontWeight: '600' },
  mapTouchZone: {
    flex: 0.25,
    backgroundColor: 'transparent',
  },

  closeBtn: {
    position: 'absolute',
    top: 14,
    right: 18,
    zIndex: 10,
  },
  closeTxt: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#000',
  },
});
